name: Build & Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nginx App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            mkdir /var/www/html/guroom_frontend
            cd /var/www/html/guroom_frontend
            git clone git@github.com:YoohaBae/GuROOM_Frontend.git
            echo 'Deployment successful to digital ocean'
            
